"""
MediaWiki does not include a word counter. I am quickly making one of my own.

This script requires some local files generated by the API calls.
"""
import os

SCRAPED_FILES_PATH = "pages/"

mastercount = 0

def count_all_textfiles(path: str):
    """
    Counts the text count of every .txt file in a given path, including subdirectories.
    This function only works in folders with only subfolders and text files. Other file types
    will lead to issues.

    ## Parameters
    path: a local path to a folder to parse through.
    ## Returns
    the number of all words across all text files in the given folder.
    """
    count = 0
    for filename in os.listdir(path):
        if "R.txt" not in filename:
            #count += count_all_textfiles(path+filename+"/")
            continue
        #else:
        with open(path + filename, 'r', encoding='utf-8') as f:
            # no need to parse out wiki formatting b/c I already did that during api calling
            count += len(f.read().strip().split(" "))
    return count

mastercount = count_all_textfiles(SCRAPED_FILES_PATH)
print(mastercount)
